# Generated by Django 5.2.4 on 2025-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/html/'),
        ),
    ]
